spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  data:
    redis:
      host: redis
      port: 6379
  profiles:
    include: oauth

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

logging.level:
  org.hibernate.SQL: debug
  org.springframework.security: debug